### ISSUE TITLE
📝 0.1.0 Release

### ISSUE THREAD

**Issue by liamnichols** [CreateAPI/CreateAPI#101]
CreateAPI has proven to be a very stable tool since its initial prerelease and to better reflect that, we're working to move to version 0.1. In doing so, we want to take this opportunity to make a few bigger than normal changes based on how the tool has been used out in the wild.

To summarise what is going into 0.1.0:

## Documentation

- [x] #70 
- [x] #58 

Up until now, there hadn't been much of a focus on documentation but that needed to change, in 0.1.0 we're writing a lot of new documentation to help new users get started with CreateAPI. 

- [x] #82 

## Configuration 

- [x] #89
- [x] #100 
- [x] #98 
- [x] #97 
- [x] #94 
- [x] #93 
- [x] #92 
- [x] #91 
- [x] #63 
- [x] #75 
- [x] #60 
- [x] #47 
- [x] #88
- [x] #66
- [x] #85 
- [x] #114

The Configuration Options are at the heart of how you tweak your generated code and its important to make sure that these options are clear and easy to understand. As a result, we'll be making some adjustments to how these options are styled which will result in some breaking changes. A complete set of notes for migration will be provided in the final release, but the aim here is to set good foundations for future changes. 

In addition, we're making it easier to figure out when your configuration file contains typos, unsupported or deprecated options:

- [x] #77
- [x] #90
- [x] #125

## Installing CreateAPI

The easier it is to install CreateAPI, the more likely you are to adopt it (I hope)

- [x] #69 
- [x] #48  

## Get 

Get recently announced the 1.0.0 release, started from CreateAPI 0.1.0, generated packages will use Get 1.0.0

- [x] #80 

## Performance Optimizations

While CreateAPI has previously focused on optimising code generation, we hadn't made much effort in terms of optimising the generated code for fast build times and slim binaries. In 0.1 we're making some changes to help with this:

- [x] #74 
- [x] #75 

It's now recommended (and the default) to split your generated entities and paths into individual source files. In addition, avoiding the generation of individual `CodingKey` enums is recommended to remove bloat from the compiled binary with larger schemas. 

---

As always, feedback and suggestions are welcome 🌟 

---

# Release Notes (Draft)

<details>
<summary>Preview</summary>

## Breaking Changes

- Generated packages and paths now depend on Get 1.0.2 or later. If you don't use Get, your `Request` type must expose an initializer that matches the [initializer defined in Get](https://github.com/kean/Get/blob/db5248ce985c703c5ea0030b7c4d3f908db304c9/Sources/Get/Request.swift#L27-L41). For more information, see [#83](https://github.com/CreateAPI/CreateAPI/pull/83).
- When generating a Swift Package, the **Package.swift** file and all other sources are written to the root of the `--output` directory instead of being nested inside a subdirectory.
- Default output directory is now **./CreateAPI**.
- The `rename.properties` option now understands property names as defined in the original schema and not after applying CreateAPI transformations (such as case conversion or swifty style booleans). For more information, see [#112](https://github.com/CreateAPI/CreateAPI/issues/112).
- The generator will now error if the path defined using `--config` did not contain a valid file (prior behaviour was to fallback to the default configuration). For more info, see [#125](https://github.com/CreateAPI/CreateAPI/pull/125).
- Command Line Argument options that alter the generate output have now been moved into the configuration file and the behaviour may have also been adjusted. Please refer to the table below for more information:

    Pre 0.1 Argument|Remark
    ---|---
    `--split` (`-s`)|This is now the default behaviour. To generate entities and structs merged into a single file, use the `mergeSources` option in the configuration file.
    `--filename-template`|Split into `entities.filenameTemplate` and `paths.filenameTemplate` in the configuration file.
    `--entityname-template`|Replaced by the `entities.nameTemplate` config option.
    `--generate`|Moved into the configuration file as `generate`. In addition, `enums` and `package` are also now valid options to consistently control the generation of all components.
    `--package`|To generate as a package, ensure that `generate` is set to `[entities, paths, enums, package]`. To customise the module name, set the `module` option.
    `--module`|To disable package generation, set `generate` to `[entities, paths]` (see above) and to customise the module name, set the `module` option.
    `--vendor`|Replaced with the `vendor` config option.
    
- Significant changes to options in the configuration file:
    
    Pre 0.1 Option|Remark
    ---|---
    `isUsingIntegersWithPredefinedCapacity`|Removed in favour of `dataTypes` customisation. Fixed width integers are now used by default so you must override the `int32` and `int64` formats if you wish to disable this.
    `isNaiveDateEnabled`|Renamed to `useNaiveDate`
    `isPluralizationEnabled`|Renamed to `pluralizeProperties`
    `isInliningTypealiases`|Renamed to `inlineTypealiases`
    `isGeneratingSwiftyBooleanPropertyNames`|Renamed to `useSwiftyPropertyNames`
    `isGeneratingEnums`|Now part of the `generate` option (included by default). 
    `isAddingDeprecations`|Renamed to `annotateDeprecations`
    `isStrippingParentNameInNestedObjects`|Renamed to `stripParentNameInNestedObjects`
    `isAddingDefaultValues`|Renamed to `includeDefaultValues`
    `isSortingPropertiesAlphabetically`|Renamed to `sortPropertiesAlphabetically`
    `isGeneratingEncodeWithEncoder`|Renamed to `alwaysIncludeEncodableImplementation`
    `isGeneratingInitWithDecoder`|Renamed to `alwaysIncludeDecodableImplementation`
    `isGeneratingInitializers`|Renamed to `includeInitializer`
    `isSkippingRedundantProtocols`|Renamed to `skipRedundantProtocols`
    `isGeneratingIdentifiableConformance`|Renamed to `includeIdentifiableConformance`
    `isRemovingRedundantPaths`|Renamed to `removeRedundantPaths`
    `isMakingOptionalPatchParametersDoubleOptional`|Renamed to `makeOptionalPatchParametersDoubleOptional`
    `isInliningSimpleQueryParameters`|Renamed to `inlineSimpleQueryParameters`
    `isInliningSimpleRequests`|Renamed to `inlineSimpleRequests`
    `isGeneratingResponseHeaders`|Renamed to `includeResponseHeaders`
    `overridenResponses`|Renamed to `overriddenResponses` (double `d`)
    `overridenBodyTypes`|Renamed to `overriddenBodyTypes` (double `d`)
    `isSwiftLintDisabled`|Removed. Use `fileHeaderComment` to replicate similar behaviour
    `isReplacingCommonAcronyms`|Replaced by `acronyms`
    `addedAcronyms`|Replaced by `acronyms`
    `ignoredAcronyms`|Replaced by `acronyms`
    `isAdditionalPropertiesOnByDefault`|Now always enabled
    `isAddingOperationIds`|Now always enabled
    `isGeneratingCustomCodingKeys`|Replaced by `optimizeCodingKeys` with different default behaviour
    `isInliningPropertiesFromReferencedSchemas`|Replaced by `inlineReferencedSchemas` with different default behaviour
    `isGeneratingMutableClassProperties`|Replaced by `mutableProperties`
    `isGeneratingMutableStructProperties`|Replaced by `mutableProperties`
    `isGeneratingStructs`|Replaced by `defaultType`
    `isMakingClassesFinal`|Replaced by `defaultType`
    `entitiesGeneratedAsClasses`|Replaced by `typeOverrides`
    `entitiesGeneratedAsStructs`|Replaced by `typeOverrides`
    `access`|Accepted values limited to `public` or `internal` (`public` is the default)

</details>

**Comment by kean** [comment]
Brilliant work with the release! 👏

**Comment by liamnichols** [comment]
Thanks! Big shoutout to @LePips too for a lot of great improvements 💪
