### ISSUE TITLE
generated package depends on an old version of Get

### ISSUE THREAD

**Issue by mgrider** [CreateAPI/CreateAPI#186]
This isn't a huge deal, but it would sure be nice to update `Get` to `2.x`. I didn't see another issue for this, so I thought I'd create one. 

There are already a few PRs pending, but this is the kind of thing I could imagine working on when I get a chance.

**Comment by liamnichols** [comment]
Thanks for raising @mgrider, `main` has already been updated to use 2.x (#154) but I hadn't gotten around to releasing a new version yet. I was hoping to get time to attend to some of the open PRs before doing so but that never happened. 

I'll release a new version shortly with the latest changes from `main` 🙏

**Comment by mgrider** [comment]
Thanks so much @liamnichols!
