### ISSUE TITLE
Tagged type for IDs?

### ISSUE THREAD

**Issue by AndrewSB** [CreateAPI/CreateAPI#188]
hey! just started using this now, i'm blown away by how good swift codegen from swagger has got in the last few years

had 2 questions as i was setting this up

1. for my ID types, i enjoy using something like https://github.com/pointfreeco/swift-tagged instead of raw Ints or Strings. is there any way to accomplish that using this generator today?
2. see #189

**Comment by LePips** [comment]
You can possibly use the trick to change the `format` for `dataTypes` to a tagged type in #176 or possibly wait for #177. I have used the `format` trick in my API and it just requires a preprocessing step to change those `format`s.
