### ISSUE TITLE
Is `Data` the correct type for properties with the `format: byte` modifier?

### ISSUE THREAD

**Issue by simorgh3196** [CreateAPI/CreateAPI#29]
The type of properties with the `format: byte` modifier has been changed to `Data` in PR #25.

However, according to the Swagger documentation, they are defined as Base64-encoded characters.
So it would be correct to treat it as a `String`, wouldn't it?

https://swagger.io/docs/specification/data-models/data-types/#format
> An optional format modifier serves as a hint at the contents and format of the string. OpenAPI defines the following built-in string formats:
...
byte – base64-encoded characters, for example, U3dhZ2dlciByb2Nrcw==

**Comment by kean** [comment]
Yes, I think you are right. I'm going to revert this change.

**Comment by liamnichols** [comment]
I was just about to revert this, but after checking, it seems that `Data` can decoded and encoded from a json string containing base64-encoded characters as described by the documentation: 

<img width="1581" alt="Screenshot 2022-06-10 at 17 30 03" src="https://user-images.githubusercontent.com/482871/173099670-a365af68-a523-46a8-a6ac-7f54e8b43f2f.png">

It doesn't seem like a necessarily bad default behaviour, it's similar to how we handle `date-time` as `Date`? 

@simorgh3196: Was this breaking something in particular for you? Maybe I missed some more details so please let me know if I did 🙏

**Comment by simorgh3196** [comment]
@liamnichols 
Thank you for your feedback.

> It doesn't seem like a necessarily bad default behaviour, it's similar to how we handle date-time as Date?

I thought that was certainly true.

I will close this Issue, thank you very much! :pray:
