### ISSUE TITLE
requestOperationIdExtension adds private extension making it inaccessible if in a separate file

### ISSUE THREAD

**Issue by andrea-gradecak** [CreateAPI/CreateAPI#42]
In [Templates.swift](https://github.com/CreateAPI/CreateAPI/blob/5225618ac7fd542fcb89d27413d568c505fa912f/Sources/CreateAPI/Generator/Templates.swift#L622), `requestOperationIdExtension` adds a private extension.

If generation creates separate files, the private extension is also in its own file `Paths+Extensions` which makes it inaccessible to use in other files.

**Comment by LePips** [comment]
Just taking a look at this, should this extension by added by default and we always generated a functional helper function:
```swift
public extension Request {
    public func settingID(_ id: String) -> Request {
        var copy = self
        copy.id = id
        return copy
    }
}
```

**Comment by liamnichols** [comment]
Could it even just be a case of removing the `private` from the existing template?

**Comment by LePips** [comment]
Or, this could be a change in Get itself as it seems more appropriate there

**Comment by liamnichols** [comment]
Using `isAddingOperationIds` will fail if the schema doesn't specify an `operationId` for one or more of its operations, which is allowed as per the spec. 

So at the moment, the flag is necessary. But that being said, I've seen other tools automatically infer the operationId from the path + method, which we could also do. And if we did, then we'd be able to just generate it automatically (or maybe just leave it as `nil`?) 

> Or, this could be a change in Get itself as it seems more appropriate there

Yeah I did think about that and it is also a possibility. It would simplify things

**Comment by LePips** [comment]
I think it would be safe to add the `operationId` as the `Request.id` by default, `nil` if none specified. Get does not use the `id` property so it's mainly for developer usage (unless I'm missing something).

**Comment by liamnichols** [comment]
Before I noticed the flag, I asked about the purpose in kean/Get#33 and you are right, it is designed for this. 

So in that case, maybe we do just pass the `id` through the convenience methods.. something like this:

```swift
public static func get(_ url: String, query: [(String, String?)]? = nil, headers: [String: String]? = nil, id: String? = nil) -> Request {
    Request(method: "GET", url: url, query: query, headers: headers, id: id)
}
```

What do you think about this @kean?

**Comment by kean** [comment]
I'm still debating how to design it. I don't think I've done a great job with all these [telescoping methods](https://github.com/kean/Get/blob/a14a6fb3ec7efe6552c78e1522d61eb9102b9861/Sources/Get/Request.swift#L53). There are too long, duplicated, and I keep forgetting the order of parameters.

I'm thinking about taking cue from SwiftUI design:

```swift
// Now
_ = Request.post(
    "/domain.tld",
    query: [("query", "value1+value2")],
    body: value,
    headers: ["a": "b"]
).withId("getDomains")

// Target state
_ = Request.post("/domain.tld", body: value)
    .query([("query", "value1+value2")])
    .headers(["a": "b"])
    .id("getDomains")
```

But I'm not sure it'll work well with the existing writable properties with the same names. It does work, but I'm sure there are going to be some issues because of the name clashes.

**Comment by kean** [comment]
Right now you can use the existing initializer for code generation purposes:

```swift
    public init(
        method: String = "GET",
        url: String,
        query: [(String, String?)]? = nil,
        body: Encodable? = nil,
        headers: [String: String]? = nil,
        id: String? = nil
    ) {
```

It didn't have the `id` parameter prior to Get 1.0, but it does now.

**Comment by liamnichols** [comment]
Thanks for the input! Ok that makes sense, the telescoping methods (TIL) methods are more for manual usage and it doesn't really matter what the generated code uses. We can generate implementations that use `Request.init(...)` directly instead 👍

**Comment by kean** [comment]
Yes, I recommend using the initializer because otherwise, you might end up using methods that'll get deprecated soon. The initializer won't change any time soon or ever.
