### ISSUE TITLE
Support escape character \r in comments

### ISSUE THREAD

**Issue by PangMo5** [CreateAPI/CreateAPI#44]
Hello, first of all, thank you for providing a awesome tool.

Recently, I tried to generate OpenAPI provided by [Jellyfin](https://github.com/jellyfin/jellyfin) with CreateAPI, but some comments had problems.
Please refer to the screenshot.

![image](https://user-images.githubusercontent.com/16532526/176367085-034faf01-577c-40e5-a8e7-2d43568d4901.png)

Probably because of `/r`.

You can check the API in https://api.jellyfin.org/openapi/jellyfin-openapi-stable.json.

**Comment by liamnichols** [comment]
Thanks for raising @PangMo5! I was able to reproduce this in the tests:

<img width="1413" alt="Screenshot 2022-06-29 at 10 09 30" src="https://user-images.githubusercontent.com/482871/176398849-6ab5c8ff-90e4-48df-aca0-169ca71d17f7.png">

Will take a look and try and put up a patch shortly
