### ISSUE TITLE
Any docs on how to actually use the generated code?

### ISSUE THREAD

**Issue by soemarko** [CreateAPI/CreateAPI#58]
I am just lost on how to actually consume my generated API.

What I've done is generate the the `Entities.swift` and `Paths.swift` drag an drop it into the project. Add Get and URLQueryEncoder via SPM. But now I'm faced with a bunch of `Cannot find type 'api' in scope`

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/381585/180772309-22a77cfb-69ee-4cb3-8346-baf84c993c3e.png">

Any info on what to do next would be nice. Thank you!

**Comment by soemarko** [comment]
Figured it out. Should've generated the code with package instead of module. And to help others that are facing the same wall here's what I did;

`$ create-api generate --output api --package api swagger.json`

Then from SPM add local package. It'll also pull Get and URLQueryEncoder as well.

Next to quickly test consuming it:
```
		let client = APIClient(baseURL: URL(string: "https://api.server.com"))
		
		Task.init(operation: {
			do {
				let response = try await client.send(api.Paths.banners.get)
				let banners = response.value.result ?? []
				
				for banner in banners {
					print(banner.imageURL)
				}
			}
			catch let error {
				print(error)
			}
		})
```

**Comment by liamnichols** [comment]
Thanks for the feedback @soemarko! I'll actually reopen this because a Getting Started guide would absolutely be useful to help in this kind of scenario 👍

**Comment by soemarko** [comment]
> Thanks for the feedback

No problem. Looking further into this, I believe most people come here from Get, so it would be easier for them. But I came here from [SwagGen](https://github.com/yonaskolb/SwagGen). So yeah, it'll be great to have some kind of docs.

**Comment by Rusik** [comment]
I wanted to play with it and faced exactly the same issue, couldn't figured out or found any docs how to actually use generated code

**Comment by mgrider** [comment]
I'll chime in and say a list of projects that use this somewhere (maybe even in the README) would also be quite useful. (I hadn't seen that `appstoreconnect-swift-sdk` project before!)
