### ISSUE TITLE
Custom Date handling

### ISSUE THREAD

**Issue by savage7** [CreateAPI/CreateAPI#59]
I have to access an API which uses non ISO date formatting. :cry: 

I've searched the documentation and the code for something like:
- provide a custom date formatter when decoding a date or date-time
- don't decode `format: date` but handle it as String. So basically ignoring the type "date" as a workaorund.

I've not found anything. Is there some option I'm missing? 

Thanks for your help, I really like CreateApi and Get, a very new fresh approach 🥇

**Comment by liamnichols** [comment]
If you are using Get, you can use the configuration block to modify the `JSONEncoder` and `JSONDecoder` which would allow you to support custom formatting behaviours.. Something like this:

```swift
let client = APIClient(baseURL: serverURL) { configuration in 
    let dateFormatter = DateFormatter()
    dateFormatter.dateFormat = "" // some format here
    dateFormatter.locale = Locale(identifier: "en_US_POSIX")

    configuration.decoder.dateDecodingStrategy = .formatted(formatter)
    configuration.encoder.dateEncodingStrategy = .formatted(formatter)
}
```

If `DateFormatter` doesn't do it for you, there are also other encoding/decoding strategies offered by Foundation that might help? 

Does that help you to achieve what you need?

**Comment by savage7** [comment]
@liamnichols Very thanks works like a charm 💯
