### ISSUE TITLE
Make `ConfigOptions.access` an enum

### ISSUE THREAD

**Issue by liamnichols** [CreateAPI/CreateAPI#66]
https://github.com/CreateAPI/CreateAPI/blob/baa71afbcfc0c5ba591eab55e07c933357c8a381/Sources/CreateOptions/ConfigOptions.swift#L63-L64

The `access` property is currently just a string meaning that you can put anything in the config file and we'll end up generating non-functioning code. 

CreateAPI will only support `public` or `internal` access levels since `open` can't be applied everywhere and `private` would just generate code that is unusable. We could model this with an enum instead.

One thing to note is that while we could specify `access: internal` in the config, we'd want to generate code without access level specifiers (i.e the same as an empty string) since the `internal` keyword itself in generated code is redundant.

For reference, we've used enums elsewhere before in `ConfigOptions` so the same pattern can be followed:

https://github.com/CreateAPI/CreateAPI/blob/baa71afbcfc0c5ba591eab55e07c933357c8a381/Sources/CreateOptions/ConfigOptions.swift#L88-L97

**Comment by LePips** [comment]
Couldn't we just assume one as default and leave the other as a flag? I would assume `public`, since people most likely will have these as a separate package and then internal can be under `isInternalAccess`.

**Comment by liamnichols** [comment]
Yeah that's also a good idea. 

It would require deprecating the old `access` flag though so might be a little tricker than I thought initially as there are a few options to potentially deprecate in the future, we might want a slightly nicer way to manage them.
