### ISSUE TITLE
Stop using swifty boolean names in configuration options

### ISSUE THREAD

**Issue by liamnichols** [CreateAPI/CreateAPI#89]
More of a question/general discussion really, but what are the thoughts regarding use of Swifty bools (`isDoingSomething` vs `doSomething`) in the configuration file? 

As a personal preference, they feel a bit out of place when in a yaml/json file. But I don't know if its me being nit picky or not. They also make it a bit harder to order the options alphabetically. 

For the upcoming 0.1.0 release, I'm considering that we might just switch the style but I want other opinions first.

**Comment by LePips** [comment]
100% 👍 from me to change

**Comment by liamnichols** [comment]
cc @kean

**Comment by kean** [comment]
I agree. They feel out of place in YAML. Please feel free to rename. 👍
