### ISSUE TITLE
Remove `isAddingOperationIds` 

### ISSUE THREAD

**Issue by liamnichols** [CreateAPI/CreateAPI#92]
After #83, `isAddingOperationIds` brings very little value since we no longer have to generate a custom extension to set `id` on `Request`.

I think it's just easier to remove the flag and always set the `id` on the `Request` if `!operationId.isEmpty`?

Are there any reasons not to do this?

**Comment by LePips** [comment]
I believe this was the consensus from #42.

**Comment by liamnichols** [comment]
Ah yes thanks for that, I forgot 😄
