### ISSUE TITLE
Simplify `acronym` related properties

### ISSUE THREAD

**Issue by liamnichols** [CreateAPI/CreateAPI#97]
Currently there are four things related to acronyms:

1. The default list (`["url", "id", "html", "ssl", "tls", "https", "http", "dns", "ftp", "api", "uuid", "json"]`)
2. `isReplacingCommonAcronyms` (defaults to `true`)
3. `addedAcronyms`
4. `ignoredAcronyms`

Its done like this to include a default set of acronyms, and then allow customisation by either disabling replacement, ignoring specific or adding new ones.

After thinking it through some more, this could be simplified down to a single configuration option:

```swift
/// A set of acronyms that should be uppercased if detected.
///
/// If you don't want to uppercase any acronyms, set this property to an empty array.
public var uppercaseAcronyms: [String] = ["url", "id", "html", "ssl", "tls", "https", "http", "dns", "ftp", "api", "uuid", "json"]
```

We provide (and document) the default set, so if the user wants to add to it, they can incorporate the set into their configuration file. 

If the user doesn't want to uppercase acronyms, they can set the property to an empty array. 

I can't see any reason not to do this?

**Comment by LePips** [comment]
Yeah that definitely cleans things up
